# Commands to start on workspace startup
tasks:
  - init: npm install
# Ports to expose on workspace startup
ports:
  - port: 6006 # Storybook
    onOpen: open-preview
    visibility: public
  - port: 3000 # npm run watch
    onOpen: open-preview
    visibility: public
