# Prevent build scripts (postinstall) from dependencies
strictDepBuilds: true

# Protection against supply chain attacks, wait 1 week before using a new package version
minimumReleaseAge: 10080

packages:
  - ./packages/config/*
  - ./packages/libraries/*
  - ./packages/domain/*
  - ./packages/infrastructure/*
  - ./packages/statistiques/*
  - ./packages/applications/*
  - ./packages/specifications

catalog:
  mediateur: 0.3.0
  zod: 4.1.9

hoistPattern:
  - '!graphql'
