openapi: 3.0.0
info:
  title: Potentiel API
  version: 0.0.0
tags: []
paths:
  /api/v1/reseaux/raccordements:
    get:
      operationId: Raccordement_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DossierRaccordementListResult'
components:
  schemas:
    DossierRaccordement:
      type: object
      required:
        - nomProjet
        - identifiantProjet
        - appelOffre
        - periode
        - famille
        - numeroCRE
        - commune
        - codePostal
        - referenceDossier
        - statutDGEC
      properties:
        nomProjet:
          type: string
        identifiantProjet:
          type: string
        appelOffre:
          type: string
        periode:
          type: string
        famille:
          type: string
        numeroCRE:
          type: string
        commune:
          type: string
        codePostal:
          type: string
        referenceDossier:
          type: string
        statutDGEC:
          type: string
    DossierRaccordementListResult:
      type: object
      required:
        - items
        - range
        - total
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/DossierRaccordement'
        range:
          $ref: '#/components/schemas/RangeOptions'
        total:
          type: integer
    RangeOptions:
      type: object
      required:
        - startPosition
        - endPosition
      properties:
        startPosition:
          type: integer
        endPosition:
          type: integer
