import { z } from 'zod';

import {
  actionnariatSchema,
  dateEchéanceOuDéliberationGfSchema,
  emailContactSchema,
  évaluationCarboneSimplifiéeSchema,
  nomCandidatSchema,
  nomProjetSchema,
  nomReprésentantLégalSchema,
  prixRéférenceSchema,
  puissanceALaPointeSchema,
  puissanceProductionAnnuelleSchema,
  sociétéMèreSchema,
  technologieSchema,
  typeGarantiesFinancieresSchema,
  choixCoefficientKSchema,
  historiqueAbandonSchema,
  obligationDeSolarisationSchema,
  puissanceDeSiteSchema,
  autorisationDUrbanismeSchema,
  installateurSchema,
  installationAvecDispositifDeStockageSchema,
  natureDeLExploitationSchema,
} from './candidatureFields.schema';
import { localitéSchema } from './localité.schema';
import { typologieInstallationSchema } from './typologieInstallation.schema';

export const dépôtSchema = z.object({
  nomProjet: nomProjetSchema,
  sociétéMère: sociétéMèreSchema,
  nomCandidat: nomCandidatSchema,
  puissanceProductionAnnuelle: puissanceProductionAnnuelleSchema,
  prixReference: prixRéférenceSchema,
  nomReprésentantLégal: nomReprésentantLégalSchema,
  emailContact: emailContactSchema,
  puissanceALaPointe: puissanceALaPointeSchema,
  evaluationCarboneSimplifiée: évaluationCarboneSimplifiéeSchema,
  actionnariat: actionnariatSchema,
  technologie: technologieSchema,
  typeGarantiesFinancières: typeGarantiesFinancieresSchema,
  dateÉchéanceGf: dateEchéanceOuDéliberationGfSchema,
  dateDélibérationGf: dateEchéanceOuDéliberationGfSchema,
  coefficientKChoisi: choixCoefficientKSchema,
  historiqueAbandon: historiqueAbandonSchema,
  obligationDeSolarisation: obligationDeSolarisationSchema,
  puissanceDeSite: puissanceDeSiteSchema,
  autorisationDUrbanisme: autorisationDUrbanismeSchema,
  installateur: installateurSchema,
  localité: localitéSchema,
  typologieInstallation: typologieInstallationSchema,
  installationAvecDispositifDeStockage: installationAvecDispositifDeStockageSchema,
  natureDeLExploitation: natureDeLExploitationSchema,
});
