import {
  fessenheim,
  batiment,
  sol,
  innovation,
  zni,
  zni2017,
  autoconsommationMetropole,
  autoconsommationMetropole2016,
  autoconsommationZNI,
  autoconsommationZNI2017,
  eolien,
  pvEolien,
  solPPE2,
  eolienPPE2,
  batimentPPE2,
  neutrePPE2,
  innovationPPE2,
  autoconsommationMetropolePPE2,
} from './appelsOffres';

export const appelsOffreStatic = [
  batiment,
  fessenheim,
  sol,
  innovation,
  zni,
  zni2017,
  autoconsommationMetropole,
  autoconsommationMetropole2016,
  autoconsommationZNI,
  autoconsommationZNI2017,
  eolien,
  pvEolien,
  solPPE2,
  eolienPPE2,
  batimentPPE2,
  neutrePPE2,
  innovationPPE2,
  autoconsommationMetropolePPE2,
];
