import { computeNombreTotalProjet } from './projet/nombreTotalProjet.statistic';
import { computePourcentageAttestationTéléchargée } from './projet/pourcentageAttestationTéléchargée.statistic';
import { computeNombrePorteurInscrit } from './utilisateur/nombrePorteurInscrit.statistic';
import { computeNombreTotalDCRDéposées } from './projet/nombreTotalDCRDéposées.statistic';
import { computePuissanceTotaleMiseEnService } from './projet/puissanceTotaleMiseEnService.stastistic';
import { computePourcentageProjetAvecDCREtPTF } from './projet/pourcentageProjetAvecDCREtPTF.statistic';
import { computePourcentageDCRDéposées } from './projet/pourcentageDCRDéposées.statistic';
import { computePourcentagePTFDéposées } from './projet/pourcentagePTFDéposées.statistic';
import { computeNombreTotalDemande } from './projet/nombreTotalDemande.statistic';
import { computeNombreDeDemandeParCategorie } from './projet/nombreDeDemandeParCategorie.statistic';
import { computeNombreDeProjetLauréatParAppelOffre } from './projet/nombreDeProjetLauréatParAppelOffre.statistic';
import { computeTotalPuissanceParAppelOffre } from './projet/totalPuissanceParAppelOffre.statistic';
import { computeNombreTotalProjetEnService } from './projet/nombreTotalProjetEnService.statistic';
import { computeProjetLauréatParDépartement } from './projet/projetLauréatParDépartement.statistic';
import { computeUtilisateurCréation } from './projet/utilisateurCréation.statistic';
import { computeTotalPuissanceProjetAvecMainlevéeAccordée } from './projet/totalPuissanceProjetAvecMainlevéeAccordée.statistic';
import { computeNombreTotalMainlevéeAccordée } from './projet/nombreTotalMainlevéeAccordée.statistic';
import { computeNombreTotalProjetAyantTransmisAttestationConformité } from './projet/nombreTotalProjetAyantTransmisAttestationConformité.statistic';
import { computeNombreTotalProjetCRE4AyantTransmisAttestationConformité } from './projet/nombreTotalProjetCRE4AyantTransmisAttestationConformité.statistic';
import { computeNombreTotalProjetPPE2AyantTransmisAttestationConformité } from './projet/nombreTotalProjetPPE2AyantTransmisAttestationConformité.statistic';
import { computePourcentageProjetEnService } from './projet/pourcentageProjetEnService.statistic';
import { computePourcentageProjetCRE4EnService } from './projet/pourcentageProjetCRE4EnService.statistic';
import { computePourcentageProjetPPE2EnService } from './projet/pourcentageProjetPPE2EnService.statistic';
import { cleanCartoProjetStatistic } from './_utils/cleanCartoProjetStatistic';
import { cleanScalarStatistic } from './_utils/cleanScalarStatistic';
import { cleanCamembertStatistic } from './_utils/cleanCamembertStatistic';
import { cleanUtilisateurStatistic } from './_utils/cleanUtilisateurStatistic';

export const cleanStatistiquesPubliques = async () => {
  await cleanCartoProjetStatistic();
  await cleanScalarStatistic();
  await cleanCamembertStatistic();
  await cleanUtilisateurStatistic();
};

export const computeStatistiquesPubliques = async () => {
  await computeNombreTotalProjet();
  await computeNombrePorteurInscrit();
  await computePourcentageAttestationTéléchargée();
  await computeNombreTotalDCRDéposées();
  await computePuissanceTotaleMiseEnService();
  await computePourcentageProjetAvecDCREtPTF();
  await computePourcentageDCRDéposées();
  await computePourcentagePTFDéposées();
  await computeNombreTotalDemande();
  await computeNombreDeDemandeParCategorie();
  await computeNombreDeProjetLauréatParAppelOffre();
  await computeTotalPuissanceParAppelOffre();
  await computeNombreTotalProjetEnService();
  await computeProjetLauréatParDépartement();
  await computeUtilisateurCréation();
  await computeTotalPuissanceProjetAvecMainlevéeAccordée();
  await computeNombreTotalMainlevéeAccordée();
  await computeNombreTotalProjetAyantTransmisAttestationConformité();
  await computeNombreTotalProjetCRE4AyantTransmisAttestationConformité();
  await computeNombreTotalProjetPPE2AyantTransmisAttestationConformité();
  await computePourcentageProjetEnService();
  await computePourcentageProjetCRE4EnService();
  await computePourcentageProjetPPE2EnService();
};
