POST http://localhost:3000/api/v1/laureats/{{identifiantProjet}}/raccordements/demande-complete-raccordement:transmettre HTTP/1.1
content-type: application/json
authorization: Bearer {{token}}

{
    "dateAccuseReception": "YYYY-MM-DD",
    "reference": "{{reference}}"
}
