#!/usr/bin/env bash
exec < /dev/tty
# Only run gitmoji on the first commit of the branch, compared to main
if [ "$(git rev-parse HEAD)" = "$(git rev-parse main)" ]; then
  ./node_modules/.bin/gitmoji --hook $1 $2
fi
