/* eslint-disable no-useless-escape */
export const allCandidatureCSVDetailsKeys = [
  '€\/MWh bonus participatif',
  'Adresse électronique du contact',
  'Adresse postale du contact',
  'Adresse',
  'Ancienne valeur 1',
  'Ancienne valeur 2',
  'Ancienne valeur 3',
  'Ancienne valeur 4',
  'Avis  (Délégation de signature)',
  'Avis  (pièce n°1)',
  'Avis  (pièce n°2)',
  'Avis  (pièce n°3)',
  'Avis  (pièce n°4)',
  'Avis  (pièce n°6)',
  'Avis  (pièce n°7)',
  'Avis (pièce n°4 AO innovation)',
  'Avis (pièce n°5 AO innovation)',
  'Avis admissibilité du projet',
  'Avis admissibilité',
  'Avis final CRE + ADEME',
  'Avis final',
  'Avis formulaire de candidature',
  'Avis garanties financières (Pièce n°5)',
  'Avis identification du candidat',
  'Candidat',
  'Capacité du raccordement (kW)',
  'CAPEX Moyen (k€ \/ MWc)',
  'Changemement Julie Benzoni',
  'Classé ?',
  'Code NACE',
  'Codes cas (AO sol)',
  'Colonne concernée 1',
  'Colonne concernée 2',
  'Colonne concernée 3',
  'Colonne concernée 4',
  'Comm 1  (pièce n°3)',
  'Comm 1  (pièce n°6)',
  'Comm 1  (pièce n°7)',
  'Comm 1 (pièce n°4 AO innovation)',
  'Comm 1 formulaire de candidature',
  'Comm 1 garanties financières (Pièce n°5)',
  'Comm 2  (pièce n°4)',
  'Comm 2  (pièce n°6)',
  'Comm 2  (pièce n°7)',
  'Comm 2 (pièce n°4 AO innovation)',
  'Comm 2 (pièce n°5 AO innovation)',
  'Comm identification du candidat',
  'Commentaire final sur note (AO innovation)',
  'Commentaire final sur note adéquation du projet avec les ambitions industrielles (AO innovation)',
  'Commentaire final sur note aspects environnementaux et sociaux (AO innovation)',
  'Commentaire final sur note degré d’innovation (AO innovation)',
  'Commentaire final sur note positionnement sur le marché  (AO innovation)',
  'Commentaire final sur note qualité technique (AO innovation)',
  'Commentaires contenu local (Installation et mise en service)',
  'Commentaires',
  'Commune (doublon)',
  'Commune',
  'Contenu local développement : Commentaires',
  'Contenu local européen (%) (Autres technologies)',
  'Contenu local européen (%) (Cellules)',
  'Contenu local européen (%) (Developpement)',
  'Contenu local européen (%) (Développement)',
  'Contenu local européen (%) (Développement)2',
  'Contenu local européen (%) (Dispositifs de stockage de l’énergie *)',
  'Contenu local européen (%) (Dispositifs de suivi de la course du soleil *)',
  'Contenu local européen (%) (fourniture, transport, montage)',
  'Contenu local européen (%) (génie civil)',
  'Contenu local européen (%) (Génie civil)',
  'Contenu local européen (%) (Installation et mise en service)',
  'Contenu local européen (%) (Modules ou films)',
  'Contenu local européen (%) (Plaquettes de silicium (wafers))',
  'Contenu local européen (%) (Polysilicium)',
  'Contenu local européen (%) (Postes de conversion)',
  'Contenu local européen (%) (raccordement)',
  'Contenu local européen (%) (Structure)',
  'Contenu local européen (%) (Turbine)',
  'Contenu local Fabrication de composants et assemblage : Commentaires',
  'Contenu local Fabrication de composants et assemblage : Pourcentage de contenu local européen (%)',
  'Contenu local Fabrication de composants et assemblage : Pourcentage de contenu local français (%)',
  'Contenu local Fabrication de composants et assemblage : Total coût du lot (M€)',
  'Contenu local français (%) (Autres technologies)',
  'Contenu local français (%) (Cellules)',
  'Contenu local français (%) (Developpement)',
  'Contenu local français (%) (Développement)',
  'Contenu local français (%) (Développement)2',
  'Contenu local français (%) (Dispositifs de stockage de l’énergie *)',
  'Contenu local français (%) (Dispositifs de suivi de la course du soleil *)',
  'Contenu local français (%) (fourniture, transport, montage)',
  'Contenu local français (%) (génie civil)',
  'Contenu local français (%) (Génie civil)',
  'Contenu local français (%) (Installation et mise en service)',
  'Contenu local français (%) (Modules ou films)',
  'Contenu local français (%) (Plaquettes de silicium (wafers))',
  'Contenu local français (%) (Polysilicium)',
  'Contenu local français (%) (Postes de conversion)',
  'Contenu local français (%) (raccordement)',
  'Contenu local français (%) (Structure)',
  'Contenu local français (%) (Turbine)',
  'Contenu local TOTAL : Commentaires',
  'Contenu local TOTAL : coût total (M€)',
  'Contenu local TOTAL : coût total (M€)2',
  'Contenu local TOTAL européen (%)',
  'Contenu local TOTAL européen (%)2',
  'Contenu local TOTAL français (%)',
  'Contenu local TOTAL français (%)2',
  'Coordonnées géodésiques WGS84 du barycentre de l’Installation : Latitude (cardinal)',
  'Coordonnées géodésiques WGS84 du barycentre de l’Installation : Latitude (degrés)',
  'Coordonnées géodésiques WGS84 du barycentre de l’Installation : Latitude (minutes)',
  'Coordonnées géodésiques WGS84 du barycentre de l’Installation : Latitude (secondes)',
  'Coordonnées géodésiques WGS84 du barycentre de l’Installation : Longitude (degrés)',
  'Coordonnées géodésiques WGS84 du barycentre de l’Installation : Longitude (minutes)',
  'Coordonnées géodésiques WGS84 du barycentre de l’Installation : Longitude (secondes)',
  'Coordonnées géodésiques WGS84du barycentre de l’Installation : Longitude (cardinal)',
  'Coordonnées géodésiques WGS84du barycentre de l’Installation : Longitude (degrés)',
  'Coordonnées géodésiques WGS84du barycentre de l’Installation : Longitude (minutes)',
  'Coordonnées géodésiques WGS84du barycentre de l’Installation : Longitude (secondes)',
  'Coût des modules €\/Wc',
  'Coût total du lot (M€) (Autres technologies)',
  'Coût total du lot (M€) (Cellules)',
  'Coût total du lot (M€) (Développement)',
  'Coût total du lot (M€) (Développement)2',
  'Coût total du lot (M€) (Dispositifs de stockage de l’énergie *)',
  'Coût total du lot (M€) (Dispositifs de suivi de la course du soleil *)',
  'Coût total du lot (M€) (fourniture, transport, montage)',
  'Coût total du lot (M€) (génie civil)',
  'Coût total du lot (M€) (Installation et mise en service )',
  'Coût total du lot (M€) (Modules ou films)',
  'Coût total du lot (M€) (Plaquettes de silicium (wafers))',
  'Coût total du lot (M€) (Polysilicium)',
  'Coût total du lot (M€) (Postes de conversion)',
  'Coût total du lot (M€) (raccordement)',
  'Coût total du lot (M€) (Structure)',
  'Coût total du lot (M€) (Turbine)',
  'Coût total du lot (Mi) (Developpement)',
  'Coût total du lot (Mi) (Génie civil)',
  'CP (doublon)',
  'CP',
  'Date  (pièce n°4)',
  'date (candidature)',
  'Date de mise en service du raccordement attendue (mm\/aaaa)',
  'Date de modification 1',
  'Date de modification 2',
  'Date de modification 3',
  'Date de modification 4',
  'Date\/Heure (candidature)',
  'Délai automatique Covid',
  'demarcheId',
  'Département',
  'Dépôt 1ère périodes précédentes ? 1',
  'Dépôt 1ère périodes précédentes ? 2',
  'Dépôt 1ère périodes précédentes ? 3',
  'Dépôt 1ère périodes précédentes ?',
  'Détention de l’Autorisation d’Urbanisme',
  'Deuxième commune si le projet est implanté sur deux communes',
  'Diamètre du rotor (m) (AO éolien)',
  'dont quantité de fonds propres (k€)',
  'Ensoleillement de référence (kWh\/m²\/an)',
  'Evaluation carbone simplifiée indiquée au C. du formulaire de candidature et arrondie (kg eq CO2\/kWc)',
  'Facteur de charges (kWh\/kWc)',
  'Famille de candidature',
  'Famille',
  'Financement collectif (Oui\/Non)',
  'Gouvernance partagée (Oui\/Non)',
  'Hauteur bout de pâle (m) (AO éolien)',
  'heure (candidature)',
  'Identification du candidat (pièce n°1)',
  'indexation_k',
  'Installation renouvellée (AO éolien)',
  'Installations agrivoltaïques',
  'Investissement ou financement participatif (Oui\/non) ?',
  'Investissement participatif (T1) ou Financement participatif (T2) participatif ?',
  'Investissement total (k€)',
  'Lieu(x) de fabrication  (Autres technologies) 1',
  'Lieu(x) de fabrication  (Autres technologies) 2',
  'Lieu(x) de fabrication  (Autres technologies) 3',
  'Lieu(x) de fabrication  (Autres technologies) 4',
  'Lieu(x) de fabrication  (Autres technologies) 5',
  'Lieu(x) de fabrication  (Autres technologies)',
  'Lieu(x) de fabrication  (dispositif de production) 1',
  'Lieu(x) de fabrication  (dispositif de production) 2',
  'Lieu(x) de fabrication  (dispositif de production) 3',
  'Lieu(x) de fabrication  (dispositif de production) 4',
  'Lieu(x) de fabrication  (dispositif de production) 5',
  'Lieu(x) de fabrication  (Dispositifs de stockage de l’énergie *) 1',
  'Lieu(x) de fabrication  (Dispositifs de stockage de l’énergie *) 2',
  'Lieu(x) de fabrication  (Dispositifs de stockage de l’énergie *) 3',
  'Lieu(x) de fabrication  (Dispositifs de stockage de l’énergie *) 4',
  'Lieu(x) de fabrication  (Dispositifs de stockage de l’énergie *)',
  'Lieu(x) de fabrication  (Dispositifs de suivi de la course du soleil *) 1',
  'Lieu(x) de fabrication  (Dispositifs de suivi de la course du soleil *) 2',
  'Lieu(x) de fabrication  (Dispositifs de suivi de la course du soleil *) 3',
  'Lieu(x) de fabrication  (Dispositifs de suivi de la course du soleil *) 4',
  'Lieu(x) de fabrication  (Dispositifs de suivi de la course du soleil *) 5',
  'Lieu(x) de fabrication  (Dispositifs de suivi de la course du soleil *)',
  'Lieu(x) de fabrication  (Modules ou films) 1',
  'Lieu(x) de fabrication  (Modules ou films) 2',
  'Lieu(x) de fabrication  (Modules ou films) 3',
  'Lieu(x) de fabrication  (Modules ou films) 4',
  'Lieu(x) de fabrication  (Modules ou films) 5',
  'Lieu(x) de fabrication  (Modules ou films)',
  'Lieu(x) de fabrication  (Plaquettes de silicium (wafers)) 1',
  'Lieu(x) de fabrication  (Plaquettes de silicium (wafers)) 2',
  'Lieu(x) de fabrication  (Plaquettes de silicium (wafers)) 3',
  'Lieu(x) de fabrication  (Plaquettes de silicium (wafers)) 4',
  'Lieu(x) de fabrication  (Plaquettes de silicium (wafers)) 5',
  'Lieu(x) de fabrication  (Plaquettes de silicium (wafers))',
  'Lieu(x) de fabrication  (Polysilicium) 1',
  'Lieu(x) de fabrication  (Polysilicium) 2',
  'Lieu(x) de fabrication  (Polysilicium) 3',
  'Lieu(x) de fabrication  (Polysilicium) 4',
  'Lieu(x) de fabrication  (Polysilicium) 5',
  'Lieu(x) de fabrication  (Polysilicium)',
  'Lieu(x) de fabrication  (Poste de conversion) 1',
  'Lieu(x) de fabrication  (Poste de conversion) 2',
  'Lieu(x) de fabrication  (Poste de conversion) 3',
  'Lieu(x) de fabrication  (Poste de conversion) 4',
  'Lieu(x) de fabrication  (Poste de conversion) 5',
  'Lieu(x) de fabrication  (Postes de conversion) 1',
  'Lieu(x) de fabrication  (Postes de conversion) 2',
  'Lieu(x) de fabrication  (Postes de conversion) 3',
  'Lieu(x) de fabrication  (Postes de conversion) 4',
  'Lieu(x) de fabrication  (Postes de conversion) 5',
  'Lieu(x) de fabrication  (Postes de conversion)',
  'Lieu(x) de fabrication  (Structure)',
  'Lieu(x) de fabrication (Cellules) 1',
  'Lieu(x) de fabrication (Cellules) 2',
  'Lieu(x) de fabrication (Cellules) 3',
  'Lieu(x) de fabrication (Cellules) 4',
  'Lieu(x) de fabrication (Cellules) 5',
  'Lieu(x) de fabrication (Cellules)',
  'Location (€\/an\/MWc)',
  'Montant estimé du raccordement (k€)',
  'Montant garanties financières (Pièce n°5)',
  'N°, voie, lieu-dit 1',
  'N°, voie, lieu-dit 2',
  'N°, voie, lieu-dit',
  'N°CRE',
  'Nature des consommateurs si autre',
  'Nature du candidat',
  'Nature et nombre du ou des consommateur(s) (AO autoconsommation)',
  'Nom (personne physique) ou raison sociale (personne morale) :',
  'Nom courrier 1',
  'Nom courrier 2',
  'Nom courrier 3',
  'Nom courrier 4',
  'Nom du fabricant  (Autres technologies) 1',
  'Nom du fabricant  (Autres technologies) 2',
  'Nom du fabricant  (Autres technologies) 3',
  'Nom du fabricant  (Autres technologies) 4',
  'Nom du fabricant  (Autres technologies) 5',
  'Nom du fabricant  (Autres technologies)',
  'Nom du fabricant  (dispositif de production) 1',
  'Nom du fabricant  (dispositif de production) 2',
  'Nom du fabricant  (dispositif de production) 3',
  'Nom du fabricant  (dispositif de production) 4',
  'Nom du fabricant  (dispositif de production) 5',
  'Nom du fabricant  (dispositif de production)',
  'Nom du fabricant  (Dispositifs de stockage de l’énergie *) 1',
  'Nom du fabricant  (Dispositifs de stockage de l’énergie *) 2',
  'Nom du fabricant  (Dispositifs de stockage de l’énergie *) 3',
  'Nom du fabricant  (Dispositifs de stockage de l’énergie *) 4',
  'Nom du fabricant  (Dispositifs de stockage de l’énergie *)',
  'Nom du fabricant  (Dispositifs de suivi de la course du soleil *) 1',
  'Nom du fabricant  (Dispositifs de suivi de la course du soleil *) 2',
  'Nom du fabricant  (Dispositifs de suivi de la course du soleil *) 3',
  'Nom du fabricant  (Dispositifs de suivi de la course du soleil *) 4',
  'Nom du fabricant  (Dispositifs de suivi de la course du soleil *) 5',
  'Nom du fabricant  (Dispositifs de suivi de la course du soleil *)',
  'Nom du fabricant  (Modules ou films) 1',
  'Nom du fabricant  (Modules ou films) 2',
  'Nom du fabricant  (Modules ou films) 3',
  'Nom du fabricant  (Modules ou films) 4',
  'Nom du fabricant  (Modules ou films) 5',
  'Nom du fabricant  (Modules ou films)',
  'Nom du fabricant  (Plaquettes de silicium (wafers)) 1',
  'Nom du fabricant  (Plaquettes de silicium (wafers)) 2',
  'Nom du fabricant  (Plaquettes de silicium (wafers)) 3',
  'Nom du fabricant  (Plaquettes de silicium (wafers)) 4',
  'Nom du fabricant  (Plaquettes de silicium (wafers)) 5',
  'Nom du fabricant  (Plaquettes de silicium (wafers))',
  'Nom du fabricant  (Polysilicium) 1',
  'Nom du fabricant  (Polysilicium) 2',
  'Nom du fabricant  (Polysilicium) 3',
  'Nom du fabricant  (Polysilicium) 4',
  'Nom du fabricant  (Polysilicium) 5',
  'Nom du fabricant  (Polysilicium)',
  'Nom du fabricant  (Poste de conversion) 1',
  'Nom du fabricant  (Poste de conversion) 2',
  'Nom du fabricant  (Poste de conversion) 3',
  'Nom du fabricant  (Poste de conversion) 4',
  'Nom du fabricant  (Poste de conversion) 5',
  'Nom du fabricant  (Poste de conversion)',
  'Nom du fabricant  (Postes de conversion) 1',
  'Nom du fabricant  (Postes de conversion) 2',
  'Nom du fabricant  (Postes de conversion) 3',
  'Nom du fabricant  (Postes de conversion) 4',
  'Nom du fabricant  (Postes de conversion) 5',
  'Nom du fabricant  (Postes de conversion)',
  'Nom du fabricant  (Structure)',
  'Nom du fabricant (Cellules) 1',
  'Nom du fabricant (Cellules) 2',
  'Nom du fabricant (Cellules) 3',
  'Nom du fabricant (Cellules) 4',
  'Nom du fabricant (Cellules) 5',
  'Nom du fabricant (Cellules)',
  'Nom du projet',
  'Nom et prénom du contact',
  'Nom et prénom du représentant légal',
  'Nom et prénom du signataire du formulaire',
  'Nom projet (doublon)',
  'Nom projet',
  'Notation de la Gouvernance Partagée',
  'Notation du Financement Collectif',
  'Note adéquation du projet avec les ambitions industrielles (\/5pt) (AO innovation)',
  'Note aspects environnementaux et sociaux (\/5pt) (AO innovation)',
  'Note AU',
  'Note carbone',
  'Note degré d’innovation (\/20pt) (AO innovation)',
  'Note environnementale',
  'Note innovation (AO innovation)',
  'Note non-défrichement',
  'Note positionnement sur le marché (\/10pt) (AO innovation)',
  'Note prix',
  'Note qualité technique (\/5pt) (AO innovation)',
  'Note totale',
  'Numéro SIREN ou SIRET*',
  'Obligation de solarisation',
  'Origine du financement collectif',
  'Oui\/non ?  (pièce n°7)',
  'Part minimale du financement collectif (%)',
  'Période',
  'pièceJustificativeGf',
  'Prix de référence (€\/MWh)',
  'Prix de référence unitaire (T0) proposé au C. du formulaire de candidature (€\/MWh)',
  'Prix Majoré',
  'prix_reference',
  'Productible annuel (MWh\/an)',
  'Puissance crête (Wc)  (Modules ou films)',
  'Puissance cumulée',
  'Puissance installé du projet indiquée au B. du formulaire de candidature (MWc)',
  'Puissance installée (MWc)',
  'Puissance unitaire des aérogénérateurs (AO éolien)',
  'puissance_production_annuelle',
  'Raccordement € \/ kWc',
  'Référence commerciale  (Autres technologies)',
  'Référence commerciale  (dispositif de production)',
  'Référence commerciale  (Modules ou films)',
  'Référence du dossier de raccordement*',
  'Reference Pli (candidature)',
  'Région',
  'Rendement nominal  (Modules ou films)',
  'Répartition exploitant agricole',
  'Répartition propriétaire foncier',
  'Revenus annuels estimés des projets',
  'Société du contact',
  'Société mère',
  'Statut demande 1',
  'Statut demande 2',
  'Statut demande 3',
  'Statut demande 4',
  'Statut',
  'Surface du Terrain d’implantation (ha)',
  'Surface projetée au sol de l’ensemble des Capteurs solaires (ha)',
  'Suspicion de 500m inter-famille ?',
  'Suspicion de doublon ? Colonnes DL à DP',
  'Suspicion de doublon ?',
  'Taux occupation toiture (AO autoconsommation)',
  'Technologie  (Dispositifs de stockage de l’énergie *)',
  'Technologie  (Dispositifs de suivi de la course du soleil *)',
  'Technologie (AO éolien)',
  'Technologie (dispositif de production)',
  'Technologie (Dispositif de stockage)',
  'Technologie (Modules ou films)',
  'Téléphone',
  'Terrain d’implantation bénéficie de la dérogation sur le c) du Cas 2 du 2.6',
  'Terrain d’implantation est dégradé au sens du cas 3 du 2.6',
  'Territoire (AO ZNI)',
  'Titre du contact',
  'Titre du représentant légal',
  'Type de consommateur associé (AO autoconsommation)',
  'Type de modification 1',
  'Type de modification 2',
  'Type de modification 3',
  'Type de modification 4',
  'Type de zone autres',
  'Type de zone pour PLU\/PLUi',
  'Type de zone pour POS',
  'Type entreprise',
  'typeImport',
  'Types Cas 3  (pièce n°3)',
  'Typologie de bâtiment',
  'Typologie de projet',
  'Valeur de l’évaluation carbone des modules (kg eq CO2\/kWc)',
  'Vérif précédentes périodes (colonnes BC à BE)',
  'Vérification montant garanties financières (Pièce n°5)',
  "1. Garantie financière jusqu'à 6 mois après la date d'achèvement  2. Garantie financière avec date butoir et à renouveler  3. Consignation",
  "1. Garantie financière jusqu'à 6 mois après la date d'achèvement 2. Garantie financière avec date d'échéance et à renouveler 3. Consignation",
  "1. Lauréat d'aucun AO 2. Abandon classique 3. Abandon avec recandidature 4. Lauréat d'un AO",
  "Appel d'offres",
  "Commentaire final sur note synergie avec l'usage agricole  (AO Innovation)",
  "Commentaire si plusieurs autorisation d'urbanisme",
  "Condition d'admissibilité ? (AO éolien)",
  "Coordonnées géodésiques WGS84 du barycentre de l'Installation : Latitude (degrés)",
  "Coordonnées géodésiques WGS84 du barycentre de l'Installation : Latitude (minutes)",
  "Coordonnées géodésiques WGS84 du barycentre de l'Installation : Latitude (secondes)",
  "Coordonnées géodésiques WGS84du barycentre de l'Installation : Longitude (degrés)",
  "Coordonnées géodésiques WGS84du barycentre de l'Installation : Longitude (minutes)",
  "Coordonnées géodésiques WGS84du barycentre de l'Installation : Longitude (secondes)",
  "Date d'échéance au format (AA\/MM\/JJJJ)",
  "Date d'échéance au format JJ\/MM\/AAAA",
  "Date d'effet garanties financières (Pièce n°5)",
  "Date d'obtention de l'autorisation d'urbanisme",
  "Date d'obtention du CETI",
  "dont quantité d'autres avantages financiers  (k€)",
  "dont quantité d'endettement  (k€)",
  "dont quantité de subventions à l'investissement  (k€)",
  "Durée prévisionnelle d'exploitation",
  "Eléments sous l'ombrière",
  "Motif d'élimination",
  "Nb d'aérogénérateurs (AO éolien)",
  "Niveau d'engagement gouvernance partagée (%)",
  "Nom de l'innovation (ADEME) (AO innovation)",
  "Note synergie avec l'usage agricole (\/10pt) (AO Innovation)",
  "Numéro de l'autorisation d'urbanisme",
  "Numéro SIRET de l'installation",
  "Période visée par certificat d'éligibilité du terrain  (pièce n°3)",
  "Région d'implantation",
  "Respect de toutes les conditions d'admissibilité ?",
  "Taux d'autoconsommation  (AO autoconsommation)",
  "Taux d'autoconsommation",
  "Taux d'occupation des toitures (%)",
  "Type d' installation agrivoltaïque",
  "Type d'AU  (pièce n°4)",
  "Type d'autorisation d'Urbanisme (pièce n°3)",
  "Type d'utorisation d'Urbanisme (pièce n°3)",
  "Type de l'innovation (ADEME) (AO innovation)",
  "Type de terrain d'implantation  (pièce n°3)",
] as const;
