name: Build on PR

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.vscode/**'
      - 'docs/**'
      - '.env.template'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
        env:
          DO_NOT_EXECUTE_MIGRATE: '1'
