name: Build on PR

on:
  pull_request:
    paths-ignore:
      - 'src/**/*.spec.ts'
      - 'src/**/*.integration.ts'
      - 'src/__tests_/**'
      - 'README.md'
      - '.github/**'
      - '.vscode/**'
      - 'legacy-features/**'
      - 'scripts/**'
      - 'devtools/**'
      - 'docs/**'
      - '.env.template'
      - '.eslint**'
      - '.prettier**'
      - 'LICENSE'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - name: 'Build the front, css, and back'
        run: npm run build:front && npm run build:css && npm run build
        env:
          NODE_ENV: production
