name: Build on PR

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.storybook/**'
      - '.vscode/**'
      - 'legacy-features/**'
      - 'scripts/**'
      - 'devtools/**'
      - 'docs/**'
      - '.env.template'
      - '.eslint**'
      - '.prettier**'
      - 'LICENSE'
      - 'src/**/*.spec.ts'
      - 'src/**/*.integration.ts'
      - 'src/__tests_/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:front
      - run: npm run build:css
      - run: npm run build
