name: Run prettier, type:check and eslint on PR

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier:check
      - run: npm run type:check
