name: Deploy to Scalingo (production)

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 📥
        uses: actions/checkout@v3

      - name: Deploy to Scalingo 🚀
        run: |
          curl -O https://cli-dl.scalingo.com/install && bash install
          scalingo login --api-token ${{ secrets.SCALINGO_TOKEN }}
          scalingo --app ${{ secrets.SCALINGO_PRODUCTION_APP }} --region ${{ secrets.SCALINGO_PRODUCTION_REGION }} integration-link-manual-deploy HEAD
