name: Pull Request workflow

on:
  pull_request:
    # NB: disabled because the checks are required and prevent merging.
    # Pending on https://github.com/orgs/community/discussions/13690
    # paths-ignore:
    # - 'README.md'
    # - '.storybook/**'
    # - '.vscode/**'
    # - 'scripts/**'
    # - 'docs/**'
    # - '.env.template'
    # - '.prettier**'
    # - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-shared-workflow:
    uses: ./.github/workflows/shared-workflow.yml
