name: Pull Request workflow

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.storybook/**'
      - '.vscode/**'
      - 'scripts/**'
      - 'docs/**'
      - '.env.template'
      - '.prettier**'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-shared-workflow:
    uses: ./.github/workflows/shared-workflow.yml
