import {
  fessenheim,
  batiment,
  sol,
  innovation,
  zni,
  zni2017,
  autoconsommationMetropole,
  autoconsommationMetropole2016,
  autoconsommationZNI,
  autoconsommationZNI2017,
  eolien,
  pvEolien,
} from './CRE4/index.js';
import {
  solPPE2,
  eolienPPE2,
  batimentPPE2,
  neutrePPE2,
  innovationPPE2,
  autoconsommationMetropolePPE2,
  zniPPE2,
  petitPVBâtimentPPE2,
} from './PPE2/index.js';

export const appelsOffreData = [
  batiment,
  fessenheim,
  sol,
  innovation,
  zni,
  zni2017,
  autoconsommationMetropole,
  autoconsommationMetropole2016,
  autoconsommationZNI,
  autoconsommationZNI2017,
  eolien,
  pvEolien,
  solPPE2,
  eolienPPE2,
  batimentPPE2,
  neutrePPE2,
  innovationPPE2,
  autoconsommationMetropolePPE2,
  zniPPE2,
  petitPVBâtimentPPE2,
];
